/**
 */
package hu.textualmodeler.grammar.scope.provider;

import hu.textualmodeler.grammar.scope.util.ScopeAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ScopeItemProviderAdapterFactory extends ScopeAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ScopeItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.textualmodeler.grammar.scope.FeatureScope} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureScopeItemProvider featureScopeItemProvider;

	/**
	 * This creates an adapter for a {@link hu.textualmodeler.grammar.scope.FeatureScope}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureScopeAdapter() {
		if (featureScopeItemProvider == null) {
			featureScopeItemProvider = new FeatureScopeItemProvider(this);
		}

		return featureScopeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.textualmodeler.grammar.scope.ContainerScope} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainerScopeItemProvider containerScopeItemProvider;

	/**
	 * This creates an adapter for a {@link hu.textualmodeler.grammar.scope.ContainerScope}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainerScopeAdapter() {
		if (containerScopeItemProvider == null) {
			containerScopeItemProvider = new ContainerScopeItemProvider(this);
		}

		return containerScopeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.textualmodeler.grammar.scope.TransitiveScope} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TransitiveScopeItemProvider transitiveScopeItemProvider;

	/**
	 * This creates an adapter for a {@link hu.textualmodeler.grammar.scope.TransitiveScope}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTransitiveScopeAdapter() {
		if (transitiveScopeItemProvider == null) {
			transitiveScopeItemProvider = new TransitiveScopeItemProvider(this);
		}

		return transitiveScopeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.textualmodeler.grammar.scope.ChainedScope} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChainedScopeItemProvider chainedScopeItemProvider;

	/**
	 * This creates an adapter for a {@link hu.textualmodeler.grammar.scope.ChainedScope}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChainedScopeAdapter() {
		if (chainedScopeItemProvider == null) {
			chainedScopeItemProvider = new ChainedScopeItemProvider(this);
		}

		return chainedScopeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.textualmodeler.grammar.scope.ConditionalScope} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConditionalScopeItemProvider conditionalScopeItemProvider;

	/**
	 * This creates an adapter for a {@link hu.textualmodeler.grammar.scope.ConditionalScope}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConditionalScopeAdapter() {
		if (conditionalScopeItemProvider == null) {
			conditionalScopeItemProvider = new ConditionalScopeItemProvider(this);
		}

		return conditionalScopeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.textualmodeler.grammar.scope.GlobalScope} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GlobalScopeItemProvider globalScopeItemProvider;

	/**
	 * This creates an adapter for a {@link hu.textualmodeler.grammar.scope.GlobalScope}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGlobalScopeAdapter() {
		if (globalScopeItemProvider == null) {
			globalScopeItemProvider = new GlobalScopeItemProvider(this);
		}

		return globalScopeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link hu.textualmodeler.grammar.scope.UnionScope} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnionScopeItemProvider unionScopeItemProvider;

	/**
	 * This creates an adapter for a {@link hu.textualmodeler.grammar.scope.UnionScope}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnionScopeAdapter() {
		if (unionScopeItemProvider == null) {
			unionScopeItemProvider = new UnionScopeItemProvider(this);
		}

		return unionScopeItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (featureScopeItemProvider != null) featureScopeItemProvider.dispose();
		if (containerScopeItemProvider != null) containerScopeItemProvider.dispose();
		if (transitiveScopeItemProvider != null) transitiveScopeItemProvider.dispose();
		if (chainedScopeItemProvider != null) chainedScopeItemProvider.dispose();
		if (conditionalScopeItemProvider != null) conditionalScopeItemProvider.dispose();
		if (globalScopeItemProvider != null) globalScopeItemProvider.dispose();
		if (unionScopeItemProvider != null) unionScopeItemProvider.dispose();
	}

}
